### ISSUE TITLE
undefined method `merge' for #<Dry::Validation::Messages::Namespaced

### ISSUE THREAD

**Issue by eduardodeoh** [hanami/validations#103]
So, i'm trying to use hanami-validations with Rails 5 app. I have a custom predicate and i need a custom message error for this.

This code:

```
predicate :unique?, message: 'error test message' do |current|
    MyModel.find_by(name: current).nil?
  end
```

generate this error: 

```
/Users/eduardo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/validations-74276a8dd4b5/lib/hanami/validations.rb:148:in `messages': undefined method `merge' for #<Dry::Validation::Messages::Namespaced:0x007f9a5f3dd5f0> (NoMethodError)
```

Is this a bug?

**Update:** The problem above occurs with inline custom predicates only. The same predicate with global custom predicate works.

**Comment by jodosha** [comment]
Hi Eduardo,
Please make sure of include master versions of dry-* gems. As an example, have a look at the Gemfile of this repository.

Does this solves the problem for you?

http://lucaguidi.com

**Comment by eduardodeoh** [comment]
@jodosha my Gemfile:

```
gem 'dry-validation', github: "dry-rb/dry-validation"
gem 'dry-types',      github: 'dry-rb/dry-types'
gem 'dry-logic',      github: 'dry-rb/dry-logic'

gem 'hanami-validations', github: "hanami/validations", branch: "master"
gem 'hanami-utils',       github: "hanami/utils",       branch: "master"
```

but I have the same problem.

**Comment by jodosha** [comment]
@eduardodeoh Thanks for the update. Right now we have a blocking issue to solve this problem: https://github.com/dry-rb/dry-validation/issues/183

We could possibly consider to remove inline predicates because they aren't proven to be stable.

This code is still changing, thanks for understanding. 😄

**Comment by eduardodeoh** [comment]
@jodosha No problems. Thank you for your support and keep your great work at hanami-validations. It's awesome.

**Comment by jodosha** [comment]
Closing this as stale ticket. @eduardodeoh Please let us to know if it still doesn't work.

**Comment by bolshakov** [comment]
Hello, gentlemen

I still experience this issue. My validation looks as follows:

```ruby
class ConfirmParams
  include Hanami::Validations::Form
  
  predicate :api_date?, message: 'must be in iso8601 format' do |value|
    ApiDate.new(value).valid?
  end

  validations do
    required(:id).filled
    required(:confirmed_at).filled(:api_date?)
  end
end
```

```ruby
# Gemfile
gem 'hanami-validations', github: 'hanami/validations', branch: 'master'
gem 'hanami-utils', github: 'hanami/utils', branch: 'master'
gem 'dry-validation', github: 'dry-rb/dry-validation'
gem 'dry-types', github: 'dry-rb/dry-types'
gem 'dry-logic', github: 'dry-rb/dry-logic'
``` 

```
# Gemfile.lock

GIT
  remote: git://github.com/dry-rb/dry-logic.git
  revision: 2d6c06e8864f4b452f9d33326969079e76f8b365
  specs:
    dry-logic (0.3.0)
      dry-container (~> 0.2, >= 0.2.6)
      dry-equalizer (~> 0.2)

GIT
  remote: git://github.com/dry-rb/dry-types.git
  revision: e0159b53b373a5dca3be2239ccdb7f4ebc6ee3a2
  specs:
    dry-types (0.8.1)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1)
      dry-container (~> 0.3)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.3, >= 0.3.0)
      dry-monads (>= 0.0.1)
      ice_nine (~> 0.11)
      inflecto (~> 0.0.0, >= 0.0.2)

GIT
  remote: git://github.com/dry-rb/dry-validation.git
  revision: 8cb156e073ec72d7d313c8f8a8d9b98d0124558b
  specs:
    dry-validation (0.9.5)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
      dry-container (~> 0.2, >= 0.2.8)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.3, >= 0.3.0)
      dry-types (~> 0.8, >= 0.8.1)

GIT
  remote: git://github.com/hanami/utils.git
  revision: 8df684643f61b9ff7b0ce7fb34e40c1bf4351ef1
  branch: master
  specs:
    hanami-utils (0.8.0)

GIT
  remote: git://github.com/hanami/validations.git
  revision: cdb128baf5f3159e968b39e2e3e638c8686ee338
  branch: master
  specs:
    hanami-validations (0.6.0)
      dry-validation (~> 0.9)
      hanami-utils (~> 0.8)
```

**Comment by jodosha** [comment]
@eduardodeoh Okay, thanks.

**Comment by wuarmin** [comment]
Just for info: the issue is limited to Inline Custom Predicates. Global Custom Predicates are working as expected.

**Comment by jodosha** [comment]
@bolshakov Please check https://github.com/hanami/validations/commit/3bbbef9c77ae666dfea50ca426356b791315ce0f I added a test where it reproduces your failing case. It seems to work well. Please let me know if it doesn't.

**Comment by rowlando** [comment]
I get the same error.

Ruby 2.3.1

```ruby
# Gemfile
source "https://rubygems.org"
gem 'hanami-validations'
```

```ruby
# Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    concurrent-ruby (1.0.2)
    dry-configurable (0.3.0)
      concurrent-ruby (~> 1.0)
    dry-container (0.5.0)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
    dry-core (0.2.0)
      concurrent-ruby (~> 1.0)
    dry-equalizer (0.2.0)
    dry-logic (0.4.0)
      dry-container (~> 0.2, >= 0.2.6)
      dry-core (~> 0.1)
      dry-equalizer (~> 0.2)
    dry-types (0.9.2)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1)
      dry-container (~> 0.3)
      dry-core (~> 0.2)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.4, >= 0.4.0)
      inflecto (~> 0.0.0, >= 0.0.2)
    dry-validation (0.10.3)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
      dry-container (~> 0.2, >= 0.2.8)
      dry-core (~> 0.1)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.4, >= 0.4.0)
      dry-types (~> 0.9, >= 0.9.0)
    hanami-utils (0.9.0)
    hanami-validations (0.7.0)
      dry-validation (~> 0.10)
      hanami-utils (~> 0.9)
    inflecto (0.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  hanami-validations

BUNDLED WITH
   1.13.2
```

```ruby
# my_validator.rb

require 'hanami-validations'
require 'hanami/validations/form'

class MyValidator
  include Hanami::Validations::Form

  predicate :url?, message: 'must be an URL' do |current|
    current.start_with?('http')
  end

  validations do
    required(:foo) { url? }
  end

end

input = { foo: 'http://hanamirb.org' }

MyValidator.new(input).validate
```

When I run `ruby my_validator.rb` the console prints this error:

```bash
/Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-validations-0.7.0/lib/hanami/validations.rb:321:in `messages': undefined method `merge' for #<Dry::Validation::Messages::Namespaced:0x007fc93926ade0> (NoMethodError)
	from /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.10.3/lib/dry/validation/schema/class_interface.rb:153:in `message_compiler'
	from /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.10.3/lib/dry/validation/schema/class_interface.rb:162:in `default_options'
	from /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.10.3/lib/dry/validation/schema/class_interface.rb:34:in `new'
	from /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-validations-0.7.0/lib/hanami/validations.rb:91:in `validations'
	from /Users/nick/Projects/testapps/predicate-validation/mediator.rb:11:in `<class:MyValidator>'
	from /Users/nick/Projects/testapps/predicate-validation/mediator.rb:4:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

**Comment by jodosha** [comment]
@rowlando Can you please try to run the tests for `hanami/validations` and share with us the results? Do they pass?

I'm interested into this: https://github.com/hanami/validations/commit/3bbbef9c77ae666dfea50ca426356b791315ce0f#diff-566f5ed8a23a936b2b725dc33587b914R86

Is there any difference with yours? Can you also please compare your `Gemfile.lock` pasted above, with the one that is generated for `hanami/validations` repository?

Thank you very much.

**Comment by rowlando** [comment]
Yes, the tests pass for `hanami/validations`.

There's no difference with my code and the code in the specs except for the fact that the code is wrapped by specs. Is there some dependency that's loaded when the tests run that is allowing it to pass? Do you get the same error when test case is run outside of a test?

The Gemfile.lock generated for `hanami/validations` is the same except for the test dependencies.

**Comment by jodosha** [comment]
@rowlando Thanks for checking. 👍 

I spotted the problem: the tests are using anonymous classes `Class.new { }`, while you're using a concrete class. In your case `klass.name` returns a not `nil` result, which is used to compose the I18n keys (eg. `my_validator.url`).

---

I opened a PR with the fix, which makes your code to work well locally.

Can you please edit your `Gemfile` like this and retry?

```ruby
source "https://rubygems.org"
gem 'hanami-validations', github: 'hanami/validations', branch: 'fix/ensure-custom-validations-to-work-with-concrete-classes-with-name'
```

Thank you. 👍

**Comment by rowlando** [comment]
Nice one! That works for me. Thanks

**Comment by jodosha** [comment]
@rowlando Thanks for checking again. Merging that then!
