### ISSUE TITLE
Is the conjunction of the array? predicate and another predicate expected to work?

### ISSUE THREAD

**Issue by rowlando** [hanami/validations#117]
The following code outputs `true`:

```ruby
# customer_validator.rb
class CustomerValidator
  include Hanami::Validations

  predicate :address?, message: 'must be address' do |current|
    current.key?(:street) && current.key?(:city)
  end

  validations do
    required(:name).filled(:str?)
    required(:addresses) { min_size?(2) }
  end

end

address = {
    street: '2 Chicken Road',
    city: 'Glasgow'
}

customer = {
    name: 'John Doe',
    addresses: [address,address]
}
puts CustomerValidator.new(customer).validate.success?
```

When I change the addresses validation to:

```ruby
required(:addresses) { array? { each { address?} } }
```

the output is `true`.

However, when combine the predicates like this:

```ruby
required(:addresses) { min_size?(2) & array? { each { address?} } }
```

I get the following error:

```bash
/Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-logic-0.4.0/lib/dry/logic/evaluator.rb:32:in `[]': no implicit conversion of Symbol into Integer (TypeError)
```

Is a conjunction of the `array?` predicate and another predicate expected to work?

**Comment by mereghost** [comment]
Hmmm... does the following work for you:

```ruby
validations do
  required(:name).filled(:str?)
  required(:addresses).filled(:min_size?(2)).each do
    required(:street).filled(:str?)
    required(:city).filled(:str?)
  end
end
```

**Comment by rowlando** [comment]
@mereghost your suggestion doesn't work as I get a syntax error. When I rewrite it to:

```ruby
validations do
  required(:name).filled(:str?)
  required(:addresses) { filled? & min_size?(2) }.each do
    required(:street).filled(:str?)
    required(:city).filled(:str?)
  end
end
```

it executes but `success?` returns `false` instead of `true`.

**Comment by mereghost** [comment]
Sorry @rowlando . I just posted the snippet from memory and that can be a bit tricky. That does work:

```ruby
validations do
  required(:name).filled(:str?)
  # this line could also be written as 
  # required(:addresses).value(min_size?: 2).each
  required(:addresses).filled(min_size?: 2).each do
    required(:street).filled(:str?)
    required(:city).filled(:str?)
  end
end
```
I'm not sure if `dry-validation` macros can be mixed with regular predicates, but probably @solnic can explain it. That being said, I do find this version way more intent revealing. If you have an `AddressValidator` somewhere (for reuse), the `each` block can simply `schema(AddressValidator)`

**Comment by rowlando** [comment]
@mereghost That snippet doesn't seem to execute the predicates in the each block. `success?` returns `true` when address is:

```ruby
address = {
    street: '2 Fox Lane',
    city: 'London'
}
```

or

```ruby
address = {
    streeeet: '2 Fox Lane',
    city: 'London'
}
```

And I can confirm that it doesn't work in the form either:

```ruby
validations do
  required(:name).filled(:str?)
  required(:addresses).filled(min_size?: 2).each do
    schema(AddressValidator)
  end
end
```

where AddressValidator is:

```ruby
class AddressValidator
  include Hanami::Validations

  validations do
    required(:street).filled(:str?)
    required(:city).filled(:str?)
  end
end
```

**Comment by mereghost** [comment]
Hmmm... that's some inconsistent behaviour, probably from `dry-validation` and macros.

I got your examples to work after some tinkering.

```ruby
class AddressValidator
  include Hanami::Validations

  validations do
    required(:street).filled(:str?)
    required(:city).filled(:str?)
  end
end

class CustomerValidator
  include Hanami::Validations

  validations do
    required(:name).filled(:str?)
    required(:addresses) { array? { min_size?(2) & each { schema AddressValidator } } }
  end
end

address = {
  stroeet: '2 Fox Lane',
  city: 'London'
}

customer = { name: 'bob', addresses: [address, address] }

p CustomerValidator.new(customer).validate.success?  #=> false. :street is missing.
```

**Comment by solnic** [comment]
this is a known issue, chaining macros is not supported. I may try to make it work, but if it turns out to be too complex, I'll just make it raise an error with some meaningful message. See https://github.com/dry-rb/dry-validation/issues/240

**Comment by mereghost** [comment]
Thanks for the clarification, @solnic =)

**Comment by rowlando** [comment]
Thanks @mereghost. Your working example really helped. Maybe the README could be updated with this example as it might help others (see https://github.com/hanami/validations/pull/118). It wasn't clear to me that this was how you could achieve my requirement.

**Comment by rowlando** [comment]
Sorry, this isn't the end :-(

`success?` correctly returns false for the following code:

```ruby
class AddressValidator
  include Hanami::Validations

  predicate :london_city?, message: 'must be London' do |current|
    current.match(/London/)
  end

  validations do
    required(:street).filled(:str?)
    required(:city) { london_city? }
  end
end

class CustomerValidator
  include Hanami::Validations

  validations do
    required(:name).filled(:str?)
    required(:addresses) { array? { min_size?(2) & each { schema AddressValidator } } }
  end
end

address = {
    street: '2 Fox Lane',
    city: 'Birmingham'
}

customer = { name: 'bob', addresses: [address, address] }

validation = CustomerValidator.new(customer).validate
p validation.success?
p validation.messages
```

but `messages` errors:

```bash
/Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:119:in `visit_predicate': message for london_city? was not found (Dry::Validation::MissingMessageError)
```

Removing the custom predicate from AddressValidator and putting the rule as inline validation works.

Is using a custom predicate within a nested schema expected to work?

**Comment by mereghost** [comment]
I think so, but there was some funny business going around inline predicates a while ago. Not sure if it was fixed (or if there was way to fix it at all), but IIRC the consensus was not to use them for now.

**Comment by solnic** [comment]
This should work:

``` ruby
required(:addresses).value(:array?, min_size?: 2) { each(AddressValidator) }
# or
required(:addresses) { array? & min_size?(2) & each(AddressValidator) }
```

we should raise an arg error when `each` receives `schema(some_schema)`

**Comment by rowlando** [comment]
@solnic Neither works. The error is:

```ruby
/Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.10.3/lib/dry/validation/schema/value.rb:184:in `block in infer_predicates': AddressValidator is not a symbol nor a string (TypeError)
```

**Comment by solnic** [comment]
@rowlando this is very weird because I tried it and it worked for me:

``` ruby
require 'dry-validation'

AddressValidator = Dry::Validation.Form do
  required(:street).filled
end

CustomerValidator = Dry::Validation.Form do
  required(:addresses) { array? & min_size?(2) & each(AddressValidator) }
end

puts CustomerValidator.(addresses: [{ street: 'foo' }, { bar: 'oops' }]).inspect
# #<Dry::Validation::Result output={:addresses=>[{:street=>"foo"}, {}]} errors={:addresses=>{1=>{:street=>["is missing"]}}}>

puts CustomerValidator.(addresses: [{ street: 'foo' }]).inspect
# #<Dry::Validation::Result output={:addresses=>[{:street=>"foo"}]} errors={:addresses=>["size cannot be less than 2"]}>
```

Maybe I missed something?

**Comment by mereghost** [comment]
@rowlando Could you get this working?

**Comment by jodosha** [comment]
I assume this is resolved. @rowlando When you can, please let us to know. Thanks.
