### ISSUE TITLE
hanami-validations is not ruby 3 compatible

### ISSUE THREAD

**Issue by johannesluedke** [hanami/validations#219]
I would like to upgrade an app with hanami-validations to Ruby 3, but because it depends on `dry-validation <0.12` which is not ruby 3 comptabile this does not work 😕

This is the erorr message shown:
```
/my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/definition.rb:33:in `initialize': wrong number of arguments (given 3, expected 1..2) (ArgumentError)
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/options.rb:17:in `new'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/options.rb:17:in `with'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/builder.rb:59:in `constructor'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:41:in `block in <module:Types>'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:40:in `each'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:40:in `<module:Types>'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:4:in `<module:Dry>'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types/core.rb:3:in `<top (required)>'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types.rb:158:in `require'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-types-0.12.3/lib/dry/types.rb:158:in `<top (required)>'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry/validation/input_processor_compiler.rb:1:in `require'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry/validation/input_processor_compiler.rb:1:in `<top (required)>'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry/validation/schema/deprecated.rb:1:in `require'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry/validation/schema/deprecated.rb:1:in `<top (required)>'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry/validation/schema.rb:14:in `require'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry/validation/schema.rb:14:in `<top (required)>'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry/validation.rb:39:in `require'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry/validation.rb:39:in `<top (required)>'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry-validation.rb:1:in `require'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/dry-validation-0.11.2/lib/dry-validation.rb:1:in `<top (required)>'
	from /my_path/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/hanami-validations-1.3.7/lib/hanami/validations.rb:3:in `require'
```

Can you upgrade the dependency to a more recent version which already has ruby 3 support? https://github.com/dry-rb/dry-types/blob/master/CHANGELOG.md#121-2019-11-07

**Comment by adam12** [comment]
It's unlikely that `hanami-validations 1.x` will support Ruby 3. My suggestion is to try the current alpha for 2.x or wait for the next new release.

**Comment by johannesluedke** [comment]
Sorry to hear that, so I guess I'll just wait 😇.. I saw https://trello.com/b/lFifnBti/hanami-20, are we days, weeks or months away from an 2.0-non-alpha/beta release?

Given that this probably blocks all hanami projects to upgrade to ruby 3, I guess this wish will come up in a lot of projects

**Comment by adam12** [comment]
> Sorry to hear that, so I guess I'll just wait

It's unfortunate, but the work involved is non-trivial and there's limited capacity which is all volunteer, and is going all towards Hanami 2.

> are we days, weeks or months away from an 2.0-non-alpha/beta release?

Things are moving along but there's really no way to tell. A lot of Hanami v2 alpha is usable and is being used by people in projects, but with the usual caveat that things may change.

There's hope for another alpha this quarter or at least next. Definitely follow Twitter or the forum for updates.
